### ISSUE TITLE
Envconfig panics if the conf struct contains an unexported field

### ISSUE THREAD

**Issue by bfontaine** [vrischmann/envconfig#5]
This test shows the issue:

```go
func TestUnexportedField(t *testing.T) {
	var conf struct {
		name string
	}

	ok(t, envconfig.Init(&conf))
}
```

Result:

```
$ go test ./...
--- FAIL: TestTest (0.00s)
panic: reflect: reflect.Value.SetString using value obtained using unexported field [recovered]
	panic: reflect: reflect.Value.SetString using value obtained using unexported field

goroutine 19 [running]:
testing.func·006()
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:441 +0x181
reflect.flag.mustBeAssignable(0xf8)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:219 +0x155
reflect.Value.SetString(0x109660, 0x2082793e0, 0xf8, 0x2082792e5, 0x3)
	/usr/local/Cellar/go/1.4.2/libexec/src/reflect/value.go:1476 +0x28
github.com/vrischmann/envconfig.parseValue(0x109660, 0x2082793e0, 0xf8, 0x2082792e5, 0x3, 0x0, 0x0)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig.go:181 +0x5e8
github.com/vrischmann/envconfig.setField(0x109660, 0x2082793e0, 0xf8, 0x16c030, 0x4, 0x0, 0x0, 0x0)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig.go:114 +0x134
github.com/vrischmann/envconfig.readStruct(0x10eb20, 0x2082793e0, 0xd9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig.go:93 +0x4c1
github.com/vrischmann/envconfig.InitWithPrefix(0xff9c0, 0x2082793e0, 0x0, 0x0, 0x0, 0x0)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig.go:39 +0x3a3
github.com/vrischmann/envconfig.Init(0xff9c0, 0x2082793e0, 0x0, 0x0)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig.go:21 +0x58
github.com/vrischmann/envconfig_test.TestTest(0x2082d0b40)
	/Users/baptiste/Go/src/github.com/vrischmann/envconfig/envconfig_test.go:276 +0x58
testing.tRunner(0x2082d0b40, 0x227090)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x1aaf88, 0x226f40, 0xf, 0xf, 0xa1ae35b5e0f21c01)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0x2082a40a0, 0x226920)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/vrischmann/envconfig/_test/_testmain.go:86 +0x1d5
FAIL	github.com/vrischmann/envconfig	0.012s
```

**Comment by vrischmann** [comment]
Fixed by 6731ebe7099c690cd30bbe4e9450ba9ed815269b. I also added a note in the documentation, that we don't support unexported fields.
